apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhtap-nodeapp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-nodeapp 
  name: rhtap-nodeapp
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rhtap-nodeapp 
